# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import spelling_bee_pb2 as spelling__bee__pb2


class SpellingBeeServiceStub(object):
    """1. This is our proto file that is used to generate our *pb2.py and *pb2_grpc.py files
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setWord = channel.unary_unary(
                '/SpellingBeeService/setWord',
                request_serializer=spelling__bee__pb2.SetWord.SerializeToString,
                response_deserializer=spelling__bee__pb2.Response.FromString,
                )
        self.createGame = channel.unary_unary(
                '/SpellingBeeService/createGame',
                request_serializer=spelling__bee__pb2.GetGame.SerializeToString,
                response_deserializer=spelling__bee__pb2.Game.FromString,
                )
        self.getWord = channel.unary_unary(
                '/SpellingBeeService/getWord',
                request_serializer=spelling__bee__pb2.GetWord.SerializeToString,
                response_deserializer=spelling__bee__pb2.Word.FromString,
                )


class SpellingBeeServiceServicer(object):
    """1. This is our proto file that is used to generate our *pb2.py and *pb2_grpc.py files
    """

    def setWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpellingBeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setWord': grpc.unary_unary_rpc_method_handler(
                    servicer.setWord,
                    request_deserializer=spelling__bee__pb2.SetWord.FromString,
                    response_serializer=spelling__bee__pb2.Response.SerializeToString,
            ),
            'createGame': grpc.unary_unary_rpc_method_handler(
                    servicer.createGame,
                    request_deserializer=spelling__bee__pb2.GetGame.FromString,
                    response_serializer=spelling__bee__pb2.Game.SerializeToString,
            ),
            'getWord': grpc.unary_unary_rpc_method_handler(
                    servicer.getWord,
                    request_deserializer=spelling__bee__pb2.GetWord.FromString,
                    response_serializer=spelling__bee__pb2.Word.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpellingBeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpellingBeeService(object):
    """1. This is our proto file that is used to generate our *pb2.py and *pb2_grpc.py files
    """

    @staticmethod
    def setWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SpellingBeeService/setWord',
            spelling__bee__pb2.SetWord.SerializeToString,
            spelling__bee__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SpellingBeeService/createGame',
            spelling__bee__pb2.GetGame.SerializeToString,
            spelling__bee__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SpellingBeeService/getWord',
            spelling__bee__pb2.GetWord.SerializeToString,
            spelling__bee__pb2.Word.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
