# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spelling_bee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spelling_bee.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12spelling_bee.proto\"\x1b\n\x07GetWord\x12\x10\n\x08get_word\x18\x01 \x01(\t\"\x1f\n\x0bReceiveWord\x12\x10\n\x08rec_word\x18\x01 \x01(\t29\n\x12SpellingBeeService\x12#\n\x07getWord\x12\x08.GetWord\x1a\x0c.ReceiveWord\"\x00\x62\x06proto3'
)




_GETWORD = _descriptor.Descriptor(
  name='GetWord',
  full_name='GetWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_word', full_name='GetWord.get_word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_RECEIVEWORD = _descriptor.Descriptor(
  name='ReceiveWord',
  full_name='ReceiveWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rec_word', full_name='ReceiveWord.rec_word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['GetWord'] = _GETWORD
DESCRIPTOR.message_types_by_name['ReceiveWord'] = _RECEIVEWORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetWord = _reflection.GeneratedProtocolMessageType('GetWord', (_message.Message,), {
  'DESCRIPTOR' : _GETWORD,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:GetWord)
  })
_sym_db.RegisterMessage(GetWord)

ReceiveWord = _reflection.GeneratedProtocolMessageType('ReceiveWord', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVEWORD,
  '__module__' : 'spelling_bee_pb2'
  # @@protoc_insertion_point(class_scope:ReceiveWord)
  })
_sym_db.RegisterMessage(ReceiveWord)



_SPELLINGBEESERVICE = _descriptor.ServiceDescriptor(
  name='SpellingBeeService',
  full_name='SpellingBeeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=84,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='getWord',
    full_name='SpellingBeeService.getWord',
    index=0,
    containing_service=None,
    input_type=_GETWORD,
    output_type=_RECEIVEWORD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPELLINGBEESERVICE)

DESCRIPTOR.services_by_name['SpellingBeeService'] = _SPELLINGBEESERVICE

# @@protoc_insertion_point(module_scope)
